config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :descriptions, only: [:index, :show, :new, :create] do
    collection do
      get :request_call
      post :submit_request_call
      get :success_request_call
    end

    member do
      get :success_upload
      get :upload_drawing
    end
  end
  resources :drawings, only: [:show, :create, :index]
  get :drawers, to: "home#drawers", as: :drawers
  get :storytellers, to: "home#storytellers", as: :storytellers
  get :about, to: "home#about", as: :about
  get :privacy, to: "home#privacy", as: :privacy

  namespace :admin do
    resources :descriptions
    resources :describers
    resources :drawings

    root to: "describers#index"
  end
end

app/models/description.rb
class Description < ApplicationRecord
  belongs_to :describer
  has_many :drawings, dependent: :destroy
  has_one_attached :recording

  validates :title, presence: true
  validates :recording, presence: true
  validate :recording_type

  delegate :name, to: :describer, prefix: true

  accepts_nested_attributes_for :describer

  scope :approved, -> { where(approved: true) }

  def full_title
    "#{describer.name}'s #{title}"
  end

  private

  def recording_type
    return unless recording.attached?
    return if recording.blob.content_type.starts_with?('audio/')

    errors.add(:recording, 'has the wrong format')
  end
end

app/controllers/admin/descriptions_controller.rb
class Admin::DescriptionsController < Admin::ApplicationController
  # Overwrite any of the RESTful controller actions to implement custom behavior
  # For example, you may want to send an email after a foo is updated.
  #
  # def update
  #   super
  #   send_foo_updated_email(requested_resource)
  # end

  # Override this method to specify custom lookup behavior.
  # This will be used to set the resource for the `show`, `edit`, and `update`
  # actions.
  #
  # def find_resource(param)
  #   Foo.find_by!(slug: param)
  # end

  # The result of this lookup will be available as `requested_resource`

  # Override this if you have certain roles that require a subset
  # this will be used to set the records shown on the `index` action.
  #
  # def scoped_resource
  #   if current_user.super_admin?
  #     resource_class
  #   else
  #     resource_class.with_less_stuff
  #   end
  # end

  # Override `resource_params` if you want to transform the submitted
  # data before it's persisted. For example, the following would turn all
  # empty values into nil values. It uses other APIs such as `resource_class`
  # and `dashboard`:
  #
  # def resource_params
  #   params.require(resource_class.model_name.param_key).
  #     permit(dashboard.permitted_attributes).
  #     transform_values { |value| value == "" ? nil : value }
  # end

  # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
  # for more information
end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController
  def index
    @descriptions = Description.approved
  end

  def show
    @description = Description.approved.find(params[:id])
    @drawings = @description.drawings.approved
  end

  def upload_drawing
    @description = Description.approved.find(params[:id])
  end

  def new
    @description = Description.new(describer: Describer.new)
  end

  def create
    @description = Description.new(description_params)
    if verify_privacy_policy && verify_recaptcha(model: @description) && @description.save
      redirect_to(success_upload_description_path(@description))
    else
      render(:new)
    end
  end

  def request_call
    @call_request = CallRequest.new
  end

  def submit_request_call
    @call_request = CallRequest.new(call_request_params)
    if verify_recaptcha(model: @call_request) && @call_request.valid?
      AdminMailer.with(call_request: @call_request).request_call.deliver_now
      redirect_to(success_request_call_descriptions_path)
    else
      render(:request_call)
    end
  end

  private

  def verify_privacy_policy
    valid = params[:privacy] == "1"
    @description.errors.add(:base, "You have to agree to the privacy policy") unless valid
    valid
  end

  def description_params
    all_params = params.require(:description)
    address_params = all_params
                       .require(:describer_attributes)
                       .extract!(:street_address, :suburb, :city, :postcode)

    all_params
      .permit(:title, :recording, describer_attributes: [:name, :email])
      .tap { |params| params[:describer_attributes].merge!(address: address_params.values.join) }
  end

  def describer_address
    params
      .require(:description)
      .require(:describer_attributes)
      .extract!(:street_address, :suburb, :city, :postcode)
      .values
      .join
  end

  def call_request_params
    params.require(:call_request).permit(:name, :email, :phone, :comment)
  end
end

app/views/descriptions/index.html.erb
<section class="section-md descriptions">
  <h2 class="with-number">Choose something to draw!</h2>

  <ul class="box-list">
    <% @descriptions.each do |description| %>
    <li>
      <%= link_to(description.full_title, description_path(description)) %>
    </li>
    <% end %>
  </ul>
</section>

app/views/descriptions/new.html.erb
<section class="section-md flex-column">
  <h2>Send us your description</h2>

  <p>
    If you have made a recording of your story, you can send it to us here.
    <br>
    Or <%= link_to('request a phone call', request_call_descriptions_path) %> and we will help you record your story over the phone.
  </p>
</section>

<section class="section-sm flex-column">
  <%= form_for(@description, html: { class: "upload-form", id: "recaptcha-form" }) do |f| %>
    <%= invisible_recaptcha_tags ui: :invisible, callback: "submitInvisibleRecaptchaForm" %>

    <div>
      <div class="file-selector" id="file-selector">
        <%= image_tag(asset_path("audio_upload_box.svg")) %>
        <label>Drag and drop your audio file here or select from your device</label>
        <%= f.file_field :recording, accept: "audio/*", id: "file-input" %>
      </div>
      <label class="filename-label" id="filename-label"></label>
    </div>

    <div>
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, placeholder: "Enter a title for this recording" %>
    </div>

    <%= f.fields_for :describer do |describer_fields| %>
      <div>
        <%= describer_fields.label :name, "First name" %>
        <%= describer_fields.text_field :name, placeholder: "Enter your first name" %>
      </div>

      <div>
        <%= describer_fields.label :email, "Email" %>
        <%= describer_fields.text_field :email, placeholder: "Email" %>
      </div>

      <h5>Or if you'd rather have drawings posted to  you, your postal address (optional)</h5>

      <div>
        <%= describer_fields.label :street_address %>
        <%= describer_fields.text_field :street_address, placeholder: "Street number, street name" %>
      </div>

      <div>
        <%= describer_fields.label :suburb %>
        <%= describer_fields.text_field :suburb, placeholder: "Suburb" %>
      </div>

      <div>
        <%= describer_fields.label :city %>
        <%= describer_fields.text_field :city, placeholder: "City" %>
      </div>

      <div>
        <%= describer_fields.label :postcode %>
        <%= describer_fields.text_field :postcode, placeholder: "Postcode" %>
      </div>
    <% end %>

    <div class="alert-box">
      <%= @description.errors.full_messages.join(", ") if @description&.errors&.any? %>
    </div>

    <div class="privacy-checkbox">
      <label>
        <%= check_box_tag(:privacy) %>
      </label>
      <small>
        Yes, I agree with the <%= link_to("Draw This! Privacy & Safety Statement", privacy_path) %>.
      </small>
    </div>

    <%= f.submit("Upload", class: "button") %>
  <% end %>
</section>

app/views/descriptions/request_call.html.erb
<section class="section-md">
  <h2>
    Request a phone call
  </h2>

  <p>
    The Draw This! team will call you either during the day or in the early
    evening to help you record your story over the phone.
  </p>
</section>

<section class="section-sm flex-column">
  <%= form_with(model: @call_request, url: submit_request_call_descriptions_path, html: { class: "form", id: "recaptcha-form" }, local: true) do |f| %>
    <%= invisible_recaptcha_tags ui: :invisible, callback: "submitInvisibleRecaptchaForm" %>

    <div>
      <%= f.label :name, "First name" %>
      <%= f.text_field :name, placeholder: "Enter your first name" %>
    </div>

    <div>
      <%= f.label :email, "Email (optional)" %>
      <%= f.text_field :email, placeholder: "Email" %>
    </div>

    <div>
      <%= f.label :phone, "Phone number" %>
      <%= f.text_field :phone, placeholder: "Phone number" %>
    </div>

    <div>
      <%= f.label :comment, "Comment (optional)" %>
      <%= f.text_area :comment, rows: 5, placeholder: "Add a comment here if there’s anything you’d like us to know..." %>
    </div>

    <div class="alert-box">
      <%= @call_request.errors.full_messages.join(", ") if @call_request&.errors&.any? %>
    </div>

    <%= f.submit("Submit", class: "button") %>
  <% end %>
</section>

app/views/descriptions/show.html.erb
<div class="section-md description">
  <h2 class="with-number">Listen and draw <%= @description.full_title %></h2>
</div>

<section class="section-sm flex-column description">
  <%= audio_tag(url_for(@description.recording), autoplay: false, controls: true, id: "description-audio") %>

  <div class="player-progress">
    <label id="player-passed">-:--</label>
    <input type="range" id="player-seeker" name="volume" min="0" max="100">
    <label id="player-left">-:--</label>
  </div>

  <ul class="playback-controls">
    <li>
      <button id="btn-play" class="button-round btn-play"></button>
    </li>
    <li>
      <button id="btn-pause" class="button-round btn-pause"></button>
    </li>
    <li>
      <button id="btn-retry" class="button-round btn-retry"></button>
    </li>
  </ul>

  <%= link_to("Next", upload_drawing_description_path(@description), class: "button center") %>
</section>

<div class="section-md description">
  <% if @drawings.count.positive? %>
    <h2>Latest drawings of <%= @description.full_title %></h2>

    <ul class="box-list">
      <% @drawings.last(10).each do |drawing| %>
        <li>
          <%= image_tag(url_for(drawing.image.variant(resize: '400>', auto_orient: true))) %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/descriptions/success_request_call.html.erb
<div class="section-md">
  <h2>
    Your request has been submitted!
  </h2>

  <p>
    The Draw This! team will call you as soon as we can, we hope within the week.
  </p>
</div>

app/views/descriptions/success_upload.html.erb
<div class="section-md">
  <h2>
    Thank you for your recording!
  </h2>

  <p>
    The Draw This! team will review your recording and email you once it's on
    the <%= link_to('Draw something page', descriptions_path) %> for kids.
  </p>
</div>

app/views/descriptions/upload_drawing.html.erb
<div class="section-md drawing-upload">
  <h2 class="with-number">
    Send my photo of <%= @description.full_title %>
    <br>
    <small>Kids, ask an adult for help!</small>
  </h2>
</div>

<section class="section-sm flex-column drawing-upload">
  <p>Take a photo of your drawing! We will share your photo in the DrawThis! Gallery and send it to <%= @description.describer_name %>.</p>

  <%= form_for(:drawing, url: drawings_path, html: { class: "upload-form", id: "recaptcha-form" }) do |f| %>
    <%= invisible_recaptcha_tags ui: :invisible, callback: "submitInvisibleRecaptchaForm" %>

    <%= hidden_field_tag :description_id, @description.id %>

    <div>
      <div class="file-selector" id="file-selector">
        <%= image_tag(asset_path("upload_box.png")) %>
        <label>Drag and drop your photo here or select from your device</label>
        <%= f.file_field :image, accept: "image/*", id: "file-input" %>
        <img id="selected-image" style="display: none;" class="selected-image" />
      </div>
      <label class="filename-label" id="filename-label"></label>
    </div>

    <div>
      <%= f.label :author, "Artist’s first name or nick name" %>
      <%= f.text_field :author, placeholder: "First name or nickname" %>
    </div>

    <div>
      <%= f.label :email, "Email (optional)" %>
      <%= f.text_field :email, placeholder: "Email" %>
      <small>The DrawThis! team may pass on a thank you message from <%= @description.describer_name %>.</small>
    </div>

    <div class="alert-box">
      <%= @drawing.errors.full_messages.join(", ") if @drawing&.errors&.any? %>
    </div>

    <div class="privacy-checkbox">
      <label>
        <%= check_box_tag(:privacy) %>
      </label>
      <small>
        Yes, as the parent or caregiver of the artist, I agree with the <%= link_to("Draw This! Privacy & Safety Statement", privacy_path) %>.
      </small>
    </div>

    <%= f.submit("Upload", class: "button") %>
  <% end %>
</section>