config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :descriptions, only: [:index, :show, :new, :create] do
    collection do
      get :request_call
      post :submit_request_call
      get :success_request_call
    end

    member do
      get :success_upload
      get :upload_drawing
    end
  end
  resources :drawings, only: [:show, :create, :index]
  get :drawers, to: "home#drawers", as: :drawers
  get :storytellers, to: "home#storytellers", as: :storytellers
  get :about, to: "home#about", as: :about
  get :privacy, to: "home#privacy", as: :privacy

  namespace :admin do
    resources :descriptions
    resources :describers
    resources :drawings

    root to: "describers#index"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
  def about; end
end

app/views/home/about.html.erb
<section class="section-sm flex-column">
  <h2>
    About
    <br />
    <small
      >DrawThis! connects the young and old through story-telling and
      art.</small
    >
  </h2>

  <p>
    If you are an older adult and would like to contribute a description so that
    a primary-schooler can have fun drawing a picture for you, <%=
    link_to("please go here for more information", storytellers_path) %>. A
    photo of the drawing will even be sent to you by post, or email or both!
  </p>

  <p>
    If you are a primary school student, you can <%= link_to('choose something
    to draw here', descriptions_path) %>.
  </p>

  <p>
    Note that we are commited to ensuring the safety of everyone who uses Draw
    This! Children and storytellers are not directly connected through our site.
    Our team approve each audio description and each drawing that gets uploaded
    to the site.
  </p>

  <p>
    DrawThis! is the winner of #HacktheCrisisNZ, April 2020. We created this
    website in a single weekend and we are improving it all the time. If you
    would like to talk with us about our idea or how you can work with us,
    please email <a href="mailto:hello@drawthis.nz">hello@drawthis.nz</a>.
  </p>
</section>

app/views/home/drawers.html.erb
<section class="section-md flex-column tutorial">
  <h2 class="with-dot">
    How it works
    <br />
    <small
      >Draw This! connects the young and old through story-telling and
      art</small
    >
  </h2>

  <ul class="box-list">
    <li>Listen</li>
    <li>Draw</li>
    <li>Upload</li>
    <li>Make people happy</li>
  </ul>

  <p>
    If you would like to do a drawing for someone, this is how it works. First,
    you can listen to people’s recordings describing their stories, objects or
    pets. Then you can draw a picture for them. When you upload a photo of your
    drawing, we send it to the describer to help make them happy.
  </p>

  <%= link_to("Get Started!", descriptions_path, class: "button center") %>
</section>

app/views/home/index.html.erb
<section class="section-md right-section flex-column index-block">
  <h1>Draw This!</h1>

  <h3>Connecting the young and old through storytelling and art.</h3>

  <div>
    <%= link_to("Draw something", drawers_path) %>
    <span>or</span>
    <%= link_to("Tell us a story", storytellers_path) %>
  </div>
</section>

app/views/home/privacy.html.erb
<section class="section-sm privacy">
  <h2>
    Privacy & Safety Statement
  </h2>

  <p>
    Your privacy is really important to us. This Privacy & Safety Statement
    tells you what information we collect, what we do with it, and the processes
    we have to keep everyone safe along in the way.
  </p>

  <p>
    Please refer to the section(s) that apply to your use of Draw This!:
  </p>

  <ol>
    <li>
      Overview: How we keep you and your information safe
    </li>
    <li>
      Privacy Statement for "Artists": People listening to descriptions and
      uploading drawings
    </li>
    <li>
      Privacy Statement for "Storytellers": People providing audio descriptions
    </li>
  </ol>

  <h3>1. Overview: How we keep your information safe</h3>

  <p>
    1.1 Our service is carefully designed to keep all Draw This! users safe.
  </p>

  <ul>
    <li>
      Artist and Storytellers cannot communicate directly using Draw This!
    </li>
    <li>
      We will not share your contact details with any other user or external
      party.
    </li>
    <li>
      All audio descriptions, photos of drawings, and "thank you" messages are
      reviewed by the Draw This! team prior to being published or shared. Please
      refer to sections 2.2 and 3.2 for more details.
    </li>
  </ul>

  <p>
    1.2 We keep your information safe by:
  </p>
  <ul>
    <li>making sure it’s protected from outside sources</li>
    <li>making regular backups of our data</li>
    <li>using the best security systems</li>
  </ul>

  <p>
    1.3 You have the right to ask for a copy of any personal information we hold
    about you, and to ask for it to be corrected if you think it is wrong. If
    you’d like to ask for a copy of your information, or to have it corrected,
    please contact us at
    <a href="mailto:hello@drawthis.nz">hello@drawthis.nz</a>.
  </p>

  <p>
    2. Privacy statement for Artists: People listening to descriptions and
    uploading drawings
  </p>

  <p>
    2.1 If you are doing a drawing for Draw This! we collect personal
    information from you, including your:
  </p>

  <ul>
    <li>first name or nickname</li>
    <li>email address</li>
  </ul>

  <p>We will also collect:</p>

  <ul>
    <li>
      a photo of your drawing ("the photo"). Please refer to section 2.4 for how
      this may relate to personal information.
    </li>
  </ul>

  <p>2.2 We collect your personal information in order to:</p>

  <p>
    Publish the photo of your drawing on the Draw This! Gallery and in the
    "Latest Drawings" gallery on the relevant audio description page.
  </p>
  <ul>
    <li>
      All photos are reviewed by the Draw This! team prior to publication on our
      website
    </li>
    <li>
      The photo will be stripped of identifying metadata (such as location
      information) and will the Gallery will not include the first name you
      provided (please see section 1.4).
    </li>
  </ul>

  <p>
    Provide Storytellers with the option to send a "thank you" message to Draw
    This!
  </p>
  <ul>
    <li>
      We will share your first name and the photo of your drawing with
      Storytellers.
    </li>
    <li>We will not share your email address.</li>
  </ul>

  <p>
    Email you a 'thank you' message we have received and reviewed from the
    Storyteller
  </p>
  <ul>
    <li>
      Prior to sending, we will review the 'thank you' message to ensure it is
      appropriate.
    </li>
  </ul>
  <p>
    Contact you to inform you of changes to this privacy statement, or any issue
    regarding the photo you have uploaded or information provided.
  </p>

  <p>2.3 Providing some information is optional.</p>

  <p>
    If you are uploading a drawing, and choose not to enter an email address, we
    will be unable to give the Storyteller the option to send a "thank you"
    message to you (please see section 1.2)
  </p>

  <p>
    2.4 When taking a photograph of your drawing, please consider what personal
    information may be included in the photo.
  </p>

  <p>
    If personal information including first name or general location (city,
    township, country) is shown in the photo (for example, in an artist
    signature),
    <i
      >we will take the inclusion of this personal information in the photo as
      your consent to share this personal information.</i
    >
  </p>
  <ul>
    <li>
      The photo will be published in the Draw This! Gallery and in the "Latest
      Drawings" gallery on the audio description page.
    </li>
  </ul>

  <p>
    Please do not include identifying personal information in your photo, such
    as people (for example, the child who did the drawing holding it up),
    surname, school name, street address, or identifible location (such as a
    street sign in the background). If personal identifying information is
    included in the photo, we will either:
  </p>
  <ul>
    <li>
      Crop or edit the photo to remove personal identifying information, and
      delete the version of the photo with identifying information from our
      system.
    </li>
    <li>
      Not accept the photo and delete it from our system. In this event, if you
      provided an email address, we will email you to notify you of this and
      request a photo without identifying personal information.
    </li>
  </ul>

  <h3>
    3. Privacy statement for Storytellers: People providing audio descriptions
  </h3>

  <p>
    3.1 If you are doing an audio description for Draw This! we collect personal
    information from you, including your:
  </p>

  <ul>
    <li>first name</li>
    <li>phone number</li>
    <li>email address and/or postal address</li>
    <li>an audio recording ("your audio description").</li>
  </ul>

  <p>3.2 We collect your personal information in order to:</p>

  <p>Record your audio description over the phone</p>
  <p>
    Publish your first name and the audio description on the Draw This! website
  </p>
  <ul>
    <li>
      All audio descriptions are reviewed by the Draw This! team prior to
      publication
    </li>
    <li>The audio recording will be stripped of identifying metadata</li>
  </ul>

  <p>
    Share photos of drawings made in response to your audio recording via email
    or post
  </p>
  <ul>
    <li>
      The Draw This! team approve all drawings prior to sending them to you
    </li>
  </ul>

  <p>
    Contact you to inform you of changes to this privacy statement, or any issue
    regarding the your audio description or the information you have provided.
  </p>

  <p>3.3 Providing some information is optional.</p>

  <p>
    If you are sharing an audio description, and choose not to provide an email
    or postal address, we will be not be able to send you any drawings.
  </p>
  <ul>
    <li>You will have to visit the Draw This! website to see the drawings</li>
    <li>
      You will be unable to provide a "thank you" message to the Draw This! Team
      to send onto Artists
    </li>
  </ul>

  <p>
    3.4 When providing your audio description, please consider what personal
    information may be included.
  </p>

  <p>
    If personal information including first name or general location (city,
    township, country) is mentioned in the description, *we will take the
    inclusion of this personal information in the audio description as your
    consent to share this personal information.*
  </p>

  <p>
    Please do not include identifying personal information in your photo, such
    as your surname, the full names of other people, or your street address. If
    personal identifying information is included in the audio description, we
    will either:
  </p>
  <ul>
    <li>
      Cut parts out of the audio description to remove personal identifying
      information, and delete the version of the description with identifying
      information from our system. We will contact you to make you aware of any
      changes we make.
    </li>
    <li>
      Not accept the description and delete it from our system. In this event,
      we will contact you to notify you of this and request a description
      without identifying personal information.
    </li>
  </ul>
</section>

app/views/home/storytellers.html.erb
<section class="section-sm flex-column">
  <h2>
    For Storytellers
  </h2>

  <p>If you would like to send us a description:</p>

  <p>
    1. Think about how you would describe your object, memory, or living thing
    to a primary- schooler.
  </p>

  <p>
    2. Think about the details, the colours, the personality, the big things,
    the little things, the things that make you smile. Some people find it
    helpful to write the description down ready to read it out. About 150 words
    is a good length for this.
  </p>

  <p>
    3. Aim to tell us your description in around 30 seconds to a minute. Speak
    clearly and unhurriedly - enjoy sharing your story!
  </p>

  <div class="storytellers-actions">
    <div>
      <p>If you have recorded a description click here to send it to us</p>
      <%= link_to("Send description", new_description_path, class: "button center") %>
    </div>

    <div>
      <p>or</p>
    </div>

    <div>
      <p>Need help? The Draw This! team can call you to make the recording</p>
      <%= link_to("Request call", request_call_descriptions_path, class: "button center") %>
    </div>
  </div>
</section>