config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :descriptions, only: [:index, :show, :new, :create] do
    collection do
      get :request_call
      post :submit_request_call
      get :success_request_call
    end

    member do
      get :success_upload
      get :upload_drawing
    end
  end
  resources :drawings, only: [:show, :create, :index]
  get :drawers, to: "home#drawers", as: :drawers
  get :storytellers, to: "home#storytellers", as: :storytellers
  get :about, to: "home#about", as: :about
  get :privacy, to: "home#privacy", as: :privacy

  namespace :admin do
    resources :descriptions
    resources :describers
    resources :drawings

    root to: "describers#index"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Draw This!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %>

    <link
      href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;600&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Nunito:wght@600;700&display=swap"
      rel="stylesheet"
    />
    <%= stylesheet_link_tag 'application', media: 'all',
    'data-turbolinks-track': 'reload' %> <%= javascript_pack_tag 'application',
    'data-turbolinks-track': 'reload' %>
  </head>

  <body class="page <%= current_page?(controller: 'home', action: 'index') ? 'with-tree' : '' %>">
    <header class="main-nav">
      <nav id="nav">
        <a class="nav-logo" href="/">Draw This!</a>

        <ul>
          <li>
            <h5><%= link_to("Draw Something", drawers_path) %></h5>
          </li>
          <li>
            <h5><%= link_to("Tell us a story", storytellers_path) %></h5>
          </li>
          <li>
            <h5><%= link_to("Gallery", drawings_path) %></h5>
          </li>
          <li>
            <h5><%= link_to("About", about_path) %></h5>
          </li>
        </ul>
      </nav>
    </header>

    <main class="content">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </main>

    <footer class="page-footer">
      <ul>
        <li>
          <%= link_to("Privacy", privacy_path) %>&nbsp;|&nbsp;
        </li>
        <li>
          Draw This! <%= Date.today.year %>
        </li>
      </ul>
    </footer>
  </body>
</html>